name: 01-ProjetoDemo_IAC

on:
  push:
    branches:
      - master
    paths:
      - 'iac/**'
  # We also want to be able to run this manually from Github
  workflow_dispatch:
  
env:
  AZ_RG_NAME: 'rg-MyProjectDemo'
  AZ_LOCATION: 'eastus'
  AZ_PLAN_SKU: 'F1'
  AZ_SERVICE_PLAN: 'asp-MyProjectDemo'
  AZ_APP_NAME: 'wapp-MyProjectDemo-app'
  AZ_API_NAME: 'wapp-MyProjectDemo-api'
  AZ_ACR_NAME: 'acrProjetoDemo'
  AZ_AKS_NAME: 'aksMyProjectDemo'
  AZ_AKS_USERNAME: 'leandro'
  AZ_AKS_KEY: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD7N8ZXEi+08cUSEVfxrkUU6jfwSQgcDxGEGdxWAz4hYHkHnv7qC+Xe2mvSitmSxUTXjVBprCGsKxvckAJl1xaeGKf0eC1gX+fVxcaAICy19MHYXE1ChTP+lqzRLeTqEGXLwOxWdrZgQmwITBza/9Yw7MHnc+VFN7xFolp0eG0cZMKMI3JyyJpODBBFZW0MTyMcHMVKzPMOo7Od7EUnK2+o/2bSOUkyc5b2qweKWparoEWUA7w5Zp9fOBL1cr9mRYFBhpnQkvgovbmSGgKn1XuN9DJRwlKDrr9o9SvKjSYIYgPEemMzivKhFUl4Okk3iOxuuQbhXSalFjpy9zvzRMl7 southamerica\\leadro@leadro-2021'
jobs:
  infra:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Azure Login
      uses: Azure/login@v1.4.4
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Deploy Template
      uses: Azure/arm-deploy@v1.0.8
      with:
        scope: resourcegroup
        resourceGroupName: ${{ env.AZ_RG_NAME }}
        template: iac/main.bicep
        deploymentMode: Incremental
        deploymentName: 'gh-actions'
        parameters: skuName=${{ env.AZ_PLAN_SKU }} servicePlan=${{ env.AZ_SERVICE_PLAN }} webAppName=${{ env.AZ_APP_NAME }} webApiName=${{ env.AZ_API_NAME }} acrName=${{ env.AZ_ACR_NAME }} aksClusterName=${{ env.AZ_AKS_NAME }} dnsPrefix=${{ env.AZ_AKS_NAME }} linuxAdminUsername=${{ env.AZ_AKS_USERNAME }}
        failOnStdErr: false
