name: 04-ProjetoDemo_Container

on:
  # We also want to be able to run this manually from Github
  workflow_dispatch:

env:
  ACR_SERVER: 'acrprojetodemo.azurecr.io'
  AZ_API_NAME_CONTAINER: 'capp-MyProjectDemo-api'
  AZ_APP_NAME_CONTAINER: 'capp-MyProjectDemo-app'
  CONTAINER_TAG: '$GITHUB_RUN_ID'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: List variables
        run: |
          echo "The default working directory on the runner, it's $GITHUB_WORKSPACE"
          echo "RUN Id = $GITHUB_RUN_ID"
          echo "RUN NUMBER = $GITHUB_RUN_NUMBER"
          echo "SHA = ${{ github.sha }}"
          ls $GITHUB_WORKSPACE

      - name: Docker Build and Push - WebApp
        run: |
          cd ./src/
          docker build -t ${{ env.ACR_SERVER }}/projetodemo.webapp:$GITHUB_RUN_NUMBER -t ${{ env.ACR_SERVER }}/projetodemo.webapp:latest -f ProjetoDemo.WebApp/Dockerfile .
          docker push --all-tags ${{ env.ACR_SERVER }}/projetodemo.webapp

      - name: Docker Build and Push - WebApi
        run: |
          cd ./src/
          docker build -t ${{ env.ACR_SERVER }}/projetodemo.webapi:$GITHUB_RUN_NUMBER -t ${{ env.ACR_SERVER }}/projetodemo.webapi:latest -f ProjetoDemo.WebApi/Dockerfile .
          docker push --all-tags ${{ env.ACR_SERVER }}/projetodemo.webapi

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Create variable
        run: |
          echo "imagem=${{ env.ACR_SERVER }}/projetodemo.webapi:$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Test variable
        run: echo $imagem

      - name: List variables
        run: |
          echo "The default working directory on the runner, it's $GITHUB_WORKSPACE"
          echo "RUN Id = $GITHUB_RUN_ID"
          echo "RUN NUMBER = $GITHUB_RUN_NUMBER"
          ls $GITHUB_WORKSPACE
          
      - uses: azure/webapps-deploy@v2
        name: Deploy API
        with:
          app-name: ${{ env.AZ_API_NAME_CONTAINER }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_API_CONTAINER }}
          images: '${{ env.ACR_SERVER }}/projetodemo.webapi:$GITHUB_RUN_NUMBER'
      
      - uses: azure/webapps-deploy@v2.2.3
        name: Deploy APP
        with:
          app-name: ${{ env.AZ_APP_NAME_CONTAINER }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_APP_CONTAINER }}
          images: "${{ env.ACR_SERVER }}/projetodemo.webapp:$GITHUB_RUN_NUMBER"