name: 06-Tests

on:
  # We also want to be able to run this manually from Github
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      
      - name: List variables
        run: |
          echo "The default working directory on the runner, it's $env:GITHUB_WORKSPACE"
          echo "RUN Id = $env:GITHUB_RUN_ID"
          echo "RUN NUMBER = $env:GITHUB_RUN_NUMBER"
        shell: pwsh
      
      - name: Environments
        run: env
        
      - name: List dir
        run: |
          dir D:\a\ProjetoDemo\ProjetoDemo
          Get-ChildItem -Path "."
        shell: pwsh
     
      - name: Run a multi-line PowerShell script
        run: |
          $psversiontable;
          Get-Process;

      - uses: lsprado/gh-composite-action@main
        with:
          int1: 8
          int2: 2
