name: 06-Tests

on:
  # We also want to be able to run this manually from Github
  workflow_dispatch:

jobs:
  build:

    #runs-on: windows-latest
    runs-on: self-hosted

    steps:
      
      - name: List variables
        run: |
          echo "The default working directory on the runner, it's $env:GITHUB_WORKSPACE"
          echo "RUN Id = $env:GITHUB_RUN_ID"
          echo "RUN NUMBER = $env:GITHUB_RUN_NUMBER"
        shell: pwsh
      
      - name: Environments
        run: env
        
      - name: List dir
        run: |
          Get-ChildItem -Path $env:GITHUB_WORKSPACE
        shell: pwsh
     
      - name: Get Process
        run: |
          $psversiontable;
          Get-Process;

      - uses: lsprado/gh-composite-action@main
        with:
          int1: 8
          int2: 2
